version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: react-select
    versions:
    - 4.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: react-toastify
    versions:
    - 7.0.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.0
