language: node_js
branches:
  only:
  - master
node_js:
 - "node"
install:
  - yarn install
script:
- yarn test
if: type = pull_request
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && yarn deploy-storybook --ci'
