nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
    tiptap-pro:
      npmRegistryServer: https://registry.tiptap.dev/
      npmPublishRegistry: https://registry.tiptap.dev/
      npmAlwaysAuth: true
      npmAuthToken: e3gC080vpbl2ksjccExYiLgvD6nbdevYPfRWp/0CUzPyCqIOLbv3dsZ31eCTUHBX
