name: S3 + Cloudfront Deploy
on:
    push:
        branches:
            - next
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: yarn install && node postinstall.js

            - name: Set up private registry
              run: yarn config set //registry.tiptap.dev/:_authToken ${{ secrets.TIPTAP_AUTH_TOKEN }}
    
            - name: Install private dependency
              run: yarn add @tiptap-pro/extension-emoji

            - name: Build Styleguidist
              run: yarn build:styleguidist

            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: styleguide
                  bucket: ${{ secrets.S3_BUCKET }}
                  bucket-region: ${{ secrets.S3_BUCKET_REGION }}
                  dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /*
                  delete-removed: true
                  no-cache: true
                  private: true
