name: S3 + Cloudfront Deploy
on:
    push:
        branches:
            - next
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Set up private registry (1/4)
              run: yarn config set npmScopes.tiptap-pro.npmAlwaysAuth "true"
            - name: Set up private registry (2/4)
              run: yarn config set npmScopes.tiptap-pro.npmAuthToken "${{ secrets.TIPTAP_AUTH_TOKEN }}"
            - name: Set up private registry (3/4)
              run: yarn config set npmScopes.tiptap-pro.npmPublishRegistry "https://registry.tiptap.dev/"
            - name: Set up private registry (4/4)
              run: yarn config set npmScopes.tiptap-pro.npmRegistryServer "https://registry.tiptap.dev/"

            - name: Install dependencies
              run: yarn install

            - name: Build Styleguidist
              run: yarn build:styleguidist

            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: styleguide
                  bucket: ${{ secrets.S3_BUCKET }}
                  bucket-region: ${{ secrets.S3_BUCKET_REGION }}
                  dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /*
                  delete-removed: true
                  no-cache: true
                  private: true
