name: S3 + Cloudfront Deploy
on:
    push:
        branches:
            - next
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        steps:
            - uses: actions/checkout@v1

            - name: Install dependencies
              run: yarn install

            - name: Build Styleguidist
              run: yarn build:styleguidist

            - name: Deploy
              uses: lbertenasco/s3-deploy@v1
              with:
                  folder: styleguidist
                  bucket: ${{ secrets.S3_BUCKET }}
                  dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: / *
