name: S3 + Cloudfront Deploy
on:
    push:
        branches:
            - next
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://registry.tiptap.dev/
              

            - name: Install dependencies
              run: yarn install && node postinstall.js
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.TIPTAP_AUTH_TOKEN }}

            - name: Build Styleguidist
              run: yarn build:styleguidist

            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: styleguide
                  bucket: ${{ secrets.S3_BUCKET }}
                  bucket-region: ${{ secrets.S3_BUCKET_REGION }}
                  dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  invalidation: /*
                  delete-removed: true
                  no-cache: true
                  private: true
